spring:
  datasource:
    url: jdbc:mysql://10.0.0.32:3306/accounts
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html

build:
  version: "1.0-local-account"