spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://10.0.0.32:3306/accounts
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true

logging:
  level:
    com:
      webnet:
        accounts: DEBUG


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "accounts"
    description: "WebNet account service"
    version: "1.0.3"

springdoc:
  swagger-ui:
    path: /swagger-ui.html


accounts:
  message: "Welcome to WbeNet Inc. Account Production is updated asap"
  contactDetails:
    name: "Gary Pay-Rent: Store Manager"
    email: "gary-pay-rent@gmail.com"
  onCallSupport:
    - (555)666-1234
    - (555)666-1234
    - (555)666-1234

build:
  version: "2.5-account-prod"
