spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:mysql://10.0.0.32:3306/cards
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include:  "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cards:
  message: "Welcome to WbeNet Inc. Cards Dev"
  contactDetails:
    name: "Gary Pay-Rent: Store Manager"
    email: "gary-pay-rent@gmail.com"
  onCallSupport:
    - (555)666-1234
    - (555)666-1234
    - (555)666-1234

build:
  version: "2.8-card-dev"