spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:mysql://10.0.0.32:3306/loans
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

loans:
  message: "Welcome to WbeNet Inc. Loan Local"
  contactDetails:
    name: "Gary Pay-Rent: Store Manager"
    email: "gary-pay-rent@gmail.com"
  onCallSupport:
    - (555)666-1234
    - (555)666-1234
    - (555)666-1234

management:
  endpoints:
    web:
      exposure:
        include:  "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

endpoints:
  shutdown:
    enabled: true

logging:
  level:
    com:
      webnet:
        loans: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  app:
    name: "loans"
    description: "WebNet loans service"
    version: "1.0.3"


springdoc:
  swagger-ui:
    path: /swagger-ui.html


build:
  version: "2.0-loan-local"
